ERROR:root:(2 points) Checking Are the curves correct?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(2 points) Checking Are the curves colored by model?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(2 points) Checking Is the legend correct?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
INFO:root:(2 points) Are the axes labels correct? is y
INFO:root:(2 points) Are the axes ranges correct? is y
INFO:root:Executed R('load(\'../../instructor/assignments/hw6/hw6-tests2.rda\')')
INFO:root:Executed R('tpr.t <- tpr(0.75, hw6$tpr.pr, hw6$tpr.tr)')
INFO:root:(2 points) R('all.equal(grade6$tpr.t, tpr.t)')[0] is True
INFO:root:(1 points) R('tpr.t>=0 & tpr.t<=1')[0] is True
INFO:root:Executed R('fpr.t <- fpr(0.75, hw6$tpr.pr, hw6$tpr.tr)')
INFO:root:(2 points) R('all.equal(grade6$fpr.t, fpr.t)')[0] is True
INFO:root:(1 points) R('fpr.t>=0 & fpr.t<=1')[0] is True
INFO:root:Executed R('plotroc.t <- plotROC(hw6$tpr.pr, hw6$tpr.tr)')
INFO:root:(2 points) R('all.equal(hw6$plotROC.t1, plotroc.t)')[0] is True
INFO:root:Executed R('response.name <- names(spam$data)[58]')
INFO:root:Executed R('n.train <- nrow(spam$train)')
INFO:root:(1 points) R('all.equal("spam", response.name)')[0] is True
INFO:root:(1 points) R('all.equal(3500, n.train)')[0] is True
ERROR:root:(2 points) Checking R('all.equal(unname(grade6$pred.rp), unname(pred.rp), check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   target is numeric, current is rpart
ERROR:root:(2 points) Checking R('all.equal(unname(grade6$pred.rf), unname(pred.rf), check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   target is numeric, current is randomForest.formula
ERROR:root:(2 points) Checking R('all.equal(grade6$min.fpr.rp, min.fpr.rp)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 248, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in mode(current) : object 'min.fpr.rp' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 248, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in mode(current) : object 'min.fpr.rp' not found

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 248, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in mode(current) : object 'min.fpr.rp' not found

ERROR:root:(2 points) Checking R('all.equal(grade6$min.fpr.rf, min.fpr.rf)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 248, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in mode(current) : object 'min.fpr.rf' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 248, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in mode(current) : object 'min.fpr.rf' not found

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 248, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in mode(current) : object 'min.fpr.rf' not found

ERROR:root:(1 points) Checking R('all.equal(grade6$rp.threshold, rp.threshold)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 248, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in mode(current) : object 'rp.threshold' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 248, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in mode(current) : object 'rp.threshold' not found

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 248, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in mode(current) : object 'rp.threshold' not found

ERROR:root:(1 points) Checking R('all.equal(grade6$rf.threshold, rf.threshold)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 248, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in mode(current) : object 'rf.threshold' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 248, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in mode(current) : object 'rf.threshold' not found

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 248, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in mode(current) : object 'rf.threshold' not found

INFO:root:You got a 14 out of 30.
